/**
 * strength-data.js — the strength program: days made of lettered blocks
 * (A, B1/B2 superset, C1/C2 superset, D finisher, ...).
 *
 * Pure data, no DOM access — same UMD pattern as data.js so it's usable
 * from Node (tests) or the browser.
 *
 * Block shape:
 *   code       "A" | "B1" | "B2" | ... — the label as written on the program
 *   name       exercise name
 *   sets       number of sets, or null for a finisher block
 *   reps       reps-per-set as written ("6", "8/side", "10/leg", ...), or
 *              null for a finisher block
 *   superset   groups blocks that alternate together (e.g. "B" links B1/B2),
 *              or null for a standalone block
 *   finisher   { format, durationMinutes } for a block that's generated by
 *              the Metcon engine instead of logged as sets — currently
 *              only block D uses this
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.MetconStrengthData = factory();
  }
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  var STRENGTH_PROGRAM = {
    days: [
      {
        id: "day1",
        name: "Day 1",
        blocks: [
          { code: "A", name: "Bench Press", sets: 4, reps: "6", superset: null, finisher: null },
          { code: "B1", name: "One-Arm DB Row", sets: 4, reps: "8/side", superset: "B", finisher: null },
          { code: "B2", name: "Bulgarian Split Squat", sets: 4, reps: "10/leg", superset: "B", finisher: null },
          { code: "C1", name: "Incline DB Bench", sets: 3, reps: "12", superset: "C", finisher: null },
          { code: "C2", name: "Romanian Deadlift", sets: 3, reps: "10", superset: "C", finisher: null },
          { code: "D", name: "Finisher", sets: null, reps: null, superset: null, finisher: { format: "amrap", durationMinutes: 8 } },
        ],
      },
      {
        id: "day2",
        name: "Day 2",
        blocks: [
          { code: "A", name: "Deadlift", sets: 4, reps: "5", superset: null, finisher: null },
          { code: "B1", name: "Strict Press", sets: 4, reps: "6", superset: "B", finisher: null },
          { code: "B2", name: "Pull-ups", sets: 5, reps: "Descending", superset: "B", finisher: null },
          { code: "C1", name: "Front Squat", sets: 3, reps: "8", superset: "C", finisher: null },
          { code: "C2", name: "Hamstring Curl", sets: 3, reps: "8", superset: "C", finisher: null },
          { code: "D", name: "Finisher", sets: null, reps: null, superset: null, finisher: { format: "amrap", durationMinutes: 14 } },
        ],
      },
      {
        id: "day3",
        name: "Day 3",
        blocks: [
          { code: "A", name: "Hack Squat", sets: 4, reps: "6", superset: null, finisher: null },
          { code: "B1", name: "DB Bench Press", sets: 4, reps: "10", superset: "B", finisher: null },
          { code: "B2", name: "Chest Supported Row", sets: 4, reps: "10", superset: "B", finisher: null },
          { code: "C1", name: "Walking Lunges", sets: 3, reps: "12/leg", superset: "C", finisher: null },
          { code: "C2", name: "Leg Raises", sets: 3, reps: "12", superset: "C", finisher: null },
          { code: "D", name: "Finisher", sets: null, reps: null, superset: null, finisher: { format: "emom", durationMinutes: 8 } },
        ],
      },
    ],
  };

  return { STRENGTH_PROGRAM: STRENGTH_PROGRAM };
});
