/**
 * strength-data.js — the strength program: days made of lettered blocks
 * (A, B1/B2 superset, C1/C2 superset, D finisher, ...), plus the 8-week
 * "Easy Strength" progression applied to each day's main lift.
 *
 * Pure data, no DOM access — same UMD pattern as data.js so it's usable
 * from Node (tests) or the browser.
 *
 * Block shape:
 *   code               "A" | "B1" | "B2" | ... — the label as written on the program
 *   name               exercise name
 *   sets, reps         a fixed lift: number of sets + reps-per-set as written
 *                       ("6", "8/side", "10/leg", ...). null on every other
 *                       kind of block.
 *   superset           groups blocks that alternate together (e.g. "B" links
 *                       B1/B2), or null for a standalone block
 *   finisher           { format, durationMinutes } for a block generated by
 *                       the Metcon engine instead of logged as sets — only
 *                       block D uses this. null on every other block.
 *   progressesWithWeek + liftKey — a main lift (the day's "A" block) whose
 *                       sets/reps/suggested-weight come from WEEK_SCHEMES
 *                       instead of a fixed prescription. liftKey points at
 *                       MAIN_LIFTS (and at the stored 1RM for that lift).
 *                       sets/reps/finisher are all null on this kind of block.
 *
 * A block is exactly one of: fixed lift, finisher, or progressesWithWeek.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.MetconStrengthData = factory();
  }
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  // The 3 lifts the 8-week "Easy Strength" progression applies to — each
  // is the "A" block of one day. id is the key both WEEK_SCHEMES-driven
  // rendering and the stored 1RMs (MetconStorage strengthMaxes) use.
  var MAIN_LIFTS = [
    { id: "benchPress", label: "Bench Press" },
    { id: "deadlift", label: "Deadlift" },
    { id: "hackSquat", label: "Hack Squat" },
  ];

  // Dan John's "Easy Strength": every week totals roughly 6-10 reps at
  // 80-90%+ of 1RM, in a different set/rep shape each week, so you get
  // heavy strength practice without ever grinding to failure. Intensity
  // ramps gently across the block; week 8 is a single heavy-single test
  // rather than another steady-state week.
  //   setReps: the reps prescribed for each set, in order (its length is
  //            the number of sets).
  //   percent: suggested %1RM for the week (rounded to the nearest 2.5kg
  //            plate when converted to a weight).
  var WEEK_SCHEMES = [
    { week: 1, label: "2 x 5", setReps: [5, 5], percent: 80 },
    { week: 2, label: "5-3-2", setReps: [5, 3, 2], percent: 82 },
    { week: 3, label: "5 x 2", setReps: [2, 2, 2, 2, 2], percent: 83 },
    { week: 4, label: "3 x 3", setReps: [3, 3, 3], percent: 85 },
    { week: 5, label: "2 x 3", setReps: [3, 3], percent: 86 },
    { week: 6, label: "3 x 2", setReps: [2, 2, 2], percent: 88 },
    { week: 7, label: "6-10 x 1", setReps: [1, 1, 1, 1, 1, 1, 1, 1], percent: 90 },
    { week: 8, label: "Heavy single (test)", setReps: [1, 1, 1, 1, 1], percent: 92, isTest: true },
  ];

  var STRENGTH_PROGRAM = {
    days: [
      {
        id: "day1",
        name: "Day 1",
        blocks: [
          { code: "A", name: "Bench Press", sets: null, reps: null, superset: null, finisher: null, progressesWithWeek: true, liftKey: "benchPress" },
          { code: "B1", name: "One-Arm DB Row", sets: 4, reps: "8/side", superset: "B", finisher: null },
          { code: "B2", name: "Bulgarian Split Squat", sets: 4, reps: "10/leg", superset: "B", finisher: null },
          { code: "C1", name: "Incline DB Bench", sets: 3, reps: "12", superset: "C", finisher: null },
          { code: "C2", name: "Romanian Deadlift", sets: 3, reps: "10", superset: "C", finisher: null },
          { code: "D", name: "Finisher", sets: null, reps: null, superset: null, finisher: { format: "amrap", durationMinutes: 8 } },
        ],
      },
      {
        id: "day2",
        name: "Day 2",
        blocks: [
          { code: "A", name: "Deadlift", sets: null, reps: null, superset: null, finisher: null, progressesWithWeek: true, liftKey: "deadlift" },
          { code: "B1", name: "Strict Press", sets: 4, reps: "6", superset: "B", finisher: null },
          { code: "B2", name: "Pull-ups", sets: 5, reps: "Descending", superset: "B", finisher: null },
          { code: "C1", name: "Front Squat", sets: 3, reps: "8", superset: "C", finisher: null },
          { code: "C2", name: "Hamstring Curl", sets: 3, reps: "8", superset: "C", finisher: null },
          { code: "D", name: "Finisher", sets: null, reps: null, superset: null, finisher: { format: "amrap", durationMinutes: 14 } },
        ],
      },
      {
        id: "day3",
        name: "Day 3",
        blocks: [
          { code: "A", name: "Hack Squat", sets: null, reps: null, superset: null, finisher: null, progressesWithWeek: true, liftKey: "hackSquat" },
          { code: "B1", name: "DB Bench Press", sets: 4, reps: "10", superset: "B", finisher: null },
          { code: "B2", name: "Chest Supported Row", sets: 4, reps: "10", superset: "B", finisher: null },
          { code: "C1", name: "Walking Lunges", sets: 3, reps: "12/leg", superset: "C", finisher: null },
          { code: "C2", name: "Leg Raises", sets: 3, reps: "12", superset: "C", finisher: null },
          { code: "D", name: "Finisher", sets: null, reps: null, superset: null, finisher: { format: "emom", durationMinutes: 8 } },
        ],
      },
    ],
  };

  return { STRENGTH_PROGRAM: STRENGTH_PROGRAM, MAIN_LIFTS: MAIN_LIFTS, WEEK_SCHEMES: WEEK_SCHEMES };
});
